apiVersion: v1
kind: Service
metadata:
  name: {{ include "triton-server.fullname" . }}
  labels:
    {{- include "triton-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  selector:
    {{- include "triton-server.selectorLabels" . | nindent 4 }}
