name: "transformer"
platform: "ensemble"
max_batch_size: 0

input {
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [-1]
}

output {
    name: "MODEL_OUTPUT"
    data_type: TYPE_FP32
    dims: [-1, -1, 50257]
}

ensemble_scheduling {
    step [
        {
            model_name: "encode"
            model_version: -1
            input_map {
                key: "TEXT"
                value: "TEXT"
            }
            output_map [
                {
                    key: "INPUT_IDS"
                    value: "INPUT_IDS"
                },
                {
                    key: "ATTENTION"
                    value: "ATTENTION"
                }
            ]
        },
        {
            model_name: "model"
            model_version: -1
            input_map [
                {
                    key: "input_ids"
                    value: "INPUT_IDS"
                },
                {
                    key: "attention_mask"
                    value: "ATTENTION"
                }
            ]
            output_map {
                key: "logits"
                value: "MODEL_OUTPUT"
            }
        }
    ]
}
